//
//  TweaksView.swift
//  Erosion
//
//  Created by lunginspector on 8/26/26.
//

import SwiftUI
import Network
import UIKit
import SafariServices


struct TweaksView: View {
    var body: some View {
        NavigationStack {
            List {
                Section {
                    NavigationLink("Custom Wallpapers", destination: PosterBoardView())
                    NavigationLink("Dialer Themer", destination: KeypadView())
                } header: {
                    HeaderLabel("Theming", symbol: "paintbrush")
                }
                
                if !isAirliftCompatibilityMode() {
                    Section {
                        if raveSupported() || weOnADebugBuild {
                            NavigationLink("MobileGestalt", destination: GestaltView())
                            NavigationLink("Advanced Key Editor", destination: AdvancedKeyEditorView())
                            NavigationLink("Config Tweaks", destination: ConfigView())
                        }
                        NavigationLink("File Operations", destination: OperationsView())
                    } header: {
                        HeaderLabel("System", symbol: "gear")
                    }
                }

                Section {
                    NavigationLink("Restriction Tweaks", destination: SupervisionRestrictionsView())
                    NavigationLink("Notification Settings", destination: SupervisionNotificationsView())
                    NavigationLink("Web Clips", destination: SupervisionWebClipsView())
                } header: {
                    HeaderLabel("Supervision", symbol: "eye")
                }

                Section {
                    NavigationLink("Airlift", destination: AirliftView())
                } header: {
                    HeaderLabel("Experimental", symbol: "flask")
                }
            }
            .navigationTitle("Tweaks")
        }
    }
}

// MARK: - Supervision / configuration-profile tweaks

private enum SupervisionProfileError: LocalizedError {
    case invalidURL
    case emptyValue
    case serverStartFailed

    var errorDescription: String? {
        switch self {
        case .invalidURL: return "The URL must begin with http:// or https://."
        case .emptyValue: return "Please fill in the required fields."
        case .serverStartFailed: return "Failed to start the local profile server."
        }
    }
}

private struct SupervisionProfile {
    let fileName: String
    let displayName: String
    let payloadType: String
    let payload: [String: Any]

    func data() throws -> Data {
        let rootUUID = UUID().uuidString
        let payloadUUID = UUID().uuidString
        var payloadDictionary = payload
        payloadDictionary["PayloadType"] = payloadType
        payloadDictionary["PayloadIdentifier"] = "com.erosion.supervision.\(payloadType).\(payloadUUID)"
        payloadDictionary["PayloadUUID"] = payloadUUID
        payloadDictionary["PayloadVersion"] = 1
        payloadDictionary["PayloadDisplayName"] = displayName
        payloadDictionary["PayloadDescription"] = "Generated by Erosion"
        payloadDictionary["PayloadOrganization"] = "Erosion"

        let root: [String: Any] = [
            "PayloadContent": [payloadDictionary],
            "PayloadDisplayName": displayName,
            "PayloadIdentifier": "com.erosion.supervision.profile.\(rootUUID)",
            "PayloadOrganization": "Erosion",
            "PayloadRemovalDisallowed": false,
            "PayloadType": "Configuration",
            "PayloadUUID": rootUUID,
            "PayloadVersion": 1
        ]
        return try PropertyListSerialization.data(fromPropertyList: root, format: .xml, options: 0)
    }
}

private final class SupervisionProfileServer: NSObject {
    private var listener: NWListener?
    private let port: NWEndpoint.Port = 51925
    private var data = Data()
    private var fileName = "profile.mobileconfig"
    private var backgroundTask: UIBackgroundTaskIdentifier = .invalid
    private var readyCompletion: ((Result<URL, Error>) -> Void)?

    func start(profile: SupervisionProfile, completion: @escaping (Result<URL, Error>) -> Void) {
        do {
            data = try profile.data()
            fileName = profile.fileName
            readyCompletion = completion

            listener?.cancel()
            listener = try NWListener(using: .tcp, on: port)

            listener?.stateUpdateHandler = { [weak self] state in
                guard let self else { return }
                switch state {
                case .ready:
                    let url = URL(string: "http://127.0.0.1:51925/")!
                    DispatchQueue.main.async {
                        self.readyCompletion?(.success(url))
                        self.readyCompletion = nil
                    }
                case .failed(let error):
                    DispatchQueue.main.async {
                        self.readyCompletion?(.failure(error))
                        self.readyCompletion = nil
                    }
                    self.stop()
                case .cancelled:
                    break
                default:
                    break
                }
            }

            listener?.newConnectionHandler = { [weak self] connection in
                guard let self else { return }
                connection.start(queue: .main)
                self.handle(connection: connection)
            }

            backgroundTask = UIApplication.shared.beginBackgroundTask(withName: "Erosion Profile Server") { [weak self] in
                self?.stop()
            }

            listener?.start(queue: .main)
        } catch {
            completion(.failure(error))
        }
    }

    private func handle(connection: NWConnection) {
        connection.receive(minimumIncompleteLength: 1, maximumLength: 65536) { [weak self, weak connection] _, _, _, _ in
            guard let self, let connection else { return }

            var response = "HTTP/1.1 200 OK\r\n"
            response += "Content-Type: application/x-apple-aspen-config\r\n"
            response += "Content-Length: \(self.data.count)\r\n"
            response += "Content-Disposition: attachment; filename=\"\(self.fileName)\"\r\n"
            response += "Pragma: no-cache\r\n"
            response += "Expires: 0\r\n"
            response += "Connection: close\r\n"
            response += "\r\n"

            var responseData = Data(response.utf8)
            responseData.append(self.data)

            connection.send(content: responseData, completion: .contentProcessed { [weak self] _ in
                connection.cancel()
                self?.stop()
            })
        }
    }

    func stop() {
        listener?.cancel()
        listener = nil
        if backgroundTask != .invalid {
            UIApplication.shared.endBackgroundTask(backgroundTask)
            backgroundTask = .invalid
        }
    }
}

private struct SupervisionSafariView: UIViewControllerRepresentable {
    let url: URL

    func makeUIViewController(context: Context) -> SFSafariViewController {
        SFSafariViewController(url: url)
    }

    func updateUIViewController(_ uiViewController: SFSafariViewController, context: Context) {}
}

private enum SupervisionInstaller {
    // Keep the server strongly retained. Lithium relies on its listener retaining
    // the server through its connection handler; we make that lifetime explicit.
    static var server: SupervisionProfileServer?

    @MainActor
    static func install(_ profile: SupervisionProfile) {
        let server = SupervisionProfileServer()
        self.server = server

        server.start(profile: profile) { result in
            switch result {
            case .success(let url):
                DispatchQueue.main.async {
                    // Use the same installation path as Lithium: present Safari's
                    // web view and let iOS handle the application/x-apple-aspen-config
                    // response as a configuration profile.
                    guard let scene = UIApplication.shared.connectedScenes
                        .compactMap({ $0 as? UIWindowScene })
                        .first(where: { $0.activationState == .foregroundActive }),
                          let window = scene.windows.first(where: { $0.isKeyWindow }),
                          var presenter = window.rootViewController else {
                        Alertinator.shared.alert(title: "Failed to install profile!", body: "Could not find the active application window.")
                        return
                    }

                    while let presented = presenter.presentedViewController {
                        presenter = presented
                    }

                    presenter.present(
                        UIHostingController(rootView: SupervisionSafariView(url: url)),
                        animated: true
                    )
                }
            case .failure(let error):
                Alertinator.shared.alert(title: "Failed to install profile!", body: error.localizedDescription)
                self.server = nil
            }
        }
    }
}

private struct SupervisionInstallButton: View {
    let profile: SupervisionProfile
    var body: some View {
        Button("Install Profile") {
            SupervisionInstaller.install(profile)
        }
    }
}

private struct SupervisionRestrictionsView: View {
    private struct Item: Identifiable {
        let id = UUID()
        let title: String
        let key: String
        let icon: String
    }

    @State private var values: [String: Bool] = [:]

    private let persistencePrefix = "Erosion.Supervision.Restriction."

    private let home = [
        Item(title: "Allow App Clips", key: "allowAppClips", icon: "app.badge"),
        Item(title: "Allow App Installation", key: "allowAppInstallation", icon: "arrow.down.app"),
        Item(title: "Allow App Removal", key: "allowAppRemoval", icon: "trash"),
        Item(title: "Allow Safari", key: "allowSafari", icon: "safari"),
        Item(title: "Allow Camera", key: "allowCamera", icon: "camera"),
        Item(title: "Allow Wallpaper Modification", key: "allowWallpaperModification", icon: "photo"),
        Item(title: "Allow Screen Shot", key: "allowScreenShot", icon: "camera.viewfinder")
    ]
    private let system = [
        Item(title: "Allow Game Center", key: "allowGameCenter", icon: "gamecontroller"),
        Item(title: "Allow Siri", key: "allowSiri", icon: "waveform"),
        Item(title: "Allow Multitasking", key: "allowMultitasking", icon: "rectangle.split.2x1"),
        Item(title: "Allow Apple Intelligence", key: "allowAppleIntelligence", icon: "apple.intelligence"),
        Item(title: "Allow NFC", key: "allowNFC", icon: "wave.3.right"),
        Item(title: "Allow AirDrop", key: "allowAirDrop", icon: "arrow.up.right.square"),
        Item(title: "Allow Paired Watch", key: "allowPairedWatch", icon: "applewatch"),
        Item(title: "Allow Profile Installation", key: "allowUIConfigurationProfileInstallation", icon: "person.text.rectangle"),
        Item(title: "Allow Account Modification", key: "allowAccountModification", icon: "person.crop.circle"),
        Item(title: "Allow Erase All Content And Settings", key: "allowEraseContentAndSettings", icon: "trash.circle")
    ]
    private let external = [
        Item(title: "Allow USB Restricted Mode", key: "allowUSBRestrictedMode", icon: "cable.connector"),
        Item(title: "Allow Proximity Setup", key: "allowProximitySetupToNewDevice", icon: "iphone.gen3.radiowaves.left.and.right")
    ]
    private let bypass = [
        Item(title: "Allow Screen Time", key: "allowScreenTime", icon: "hourglass"),
        Item(title: "Allow Classroom", key: "allowClassroom", icon: "person.3"),
        Item(title: "Allow Explicit Content", key: "allowExplicitContent", icon: "exclamationmark.triangle")
    ]

    var body: some View {
        List {
            Section {
                Text("These settings are delivered as an Apple configuration profile and require a supervised device.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            restrictionSection("Home Screen & Apps", items: home)
            restrictionSection("System", items: system)
            restrictionSection("External Features", items: external)
            restrictionSection("Bypass Features", items: bypass)
            Section {
                SupervisionInstallButton(profile: makeProfile())
            }
        }
        .navigationTitle("Restriction Tweaks")
        .onAppear {
            for item in home + system + external + bypass {
                let key = persistencePrefix + item.key
                if UserDefaults.standard.object(forKey: key) == nil {
                    values[item.key] = true
                    UserDefaults.standard.set(true, forKey: key)
                } else {
                    values[item.key] = UserDefaults.standard.bool(forKey: key)
                }
            }
        }
    }

    @ViewBuilder
    private func restrictionSection(_ title: String, items: [Item]) -> some View {
        Section {
            ForEach(items) { item in
                Toggle(isOn: Binding(
                    get: { values[item.key] ?? true },
                    set: { newValue in
                        values[item.key] = newValue
                        UserDefaults.standard.set(newValue, forKey: persistencePrefix + item.key)
                    }
                )) {
                    Label(item.title, systemImage: item.icon)
                }
            }
        } header: {
            HeaderLabel(title, symbol: "slider.horizontal.3")
        }
    }

    private func makeProfile() -> SupervisionProfile {
        var payload: [String: Any] = [:]
        for item in home + system + external + bypass { payload[item.key] = values[item.key] ?? true }
        payload["allowScreenTime"] = values["allowScreenTime"] ?? true
        payload["allowClassroom"] = values["allowClassroom"] ?? true
        payload["allowExplicitContent"] = values["allowExplicitContent"] ?? true
        return SupervisionProfile(fileName: "Erosion-Restrictions.mobileconfig", displayName: "Erosion Restriction Tweaks", payloadType: "com.apple.applicationaccess", payload: payload)
    }
}

private struct SupervisionNotificationsView: View {
    private struct AppSetting: Identifiable, Codable {
        var id = UUID()
        var bundleID = ""
        var notifications = true
        var notificationCenter = true
        var lockScreen = true
        var badges = true
        var sounds = true
        var carPlay = true
    }

    @State private var apps: [AppSetting] = []

    var body: some View {
        List {
            Section {
                Text("Notification settings are enforced by a supervised configuration profile. Add an app by its bundle identifier, then install the generated profile.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            Section {
                ForEach($apps) { $app in
                    VStack(alignment: .leading, spacing: 15) {
                        HStack {
                            TextField("Bundle Identifier", text: $app.bundleID)
                                .textInputAutocapitalization(.never)
                                .autocorrectionDisabled()
                            Button(role: .destructive) {
                                apps.removeAll { $0.id == app.id }
                            } label: { Image(systemName: "minus.circle.fill") }
                                .buttonStyle(.plain)
                        }
                        Toggle("Notifications Enabled", isOn: $app.notifications)
                        Toggle("Notification Center", isOn: $app.notificationCenter)
                        Toggle("Lock Screen", isOn: $app.lockScreen)
                        Toggle("Badges", isOn: $app.badges)
                        Toggle("Sounds", isOn: $app.sounds)
                        Toggle("CarPlay", isOn: $app.carPlay)
                    }
                    .padding(.vertical, 9)
                }
                Button {
                    apps.append(AppSetting())
                } label: {
                    Label("Add Application", systemImage: "plus")
                }
            } header: {
                HeaderLabel("Applications", symbol: "app.badge")
            }
            Section {
                Button("Install Profile") {
                    guard apps.allSatisfy({ !$0.bundleID.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }) else {
                        Alertinator.shared.alert(title: "Missing Bundle Identifier", body: "Every notification entry needs a bundle identifier.")
                        return
                    }
                    let settings: [[String: Any]] = apps.map { app in
                        [
                            "BundleIdentifier": app.bundleID,
                            "NotificationsEnabled": app.notifications,
                            "ShowInNotificationCenter": app.notificationCenter,
                            "ShowInLockScreen": app.lockScreen,
                            "BadgesEnabled": app.badges,
                            "SoundsEnabled": app.sounds,
                            "ShowInCarPlay": app.carPlay
                        ]
                    }
                    let profile = SupervisionProfile(fileName: "Erosion-Notifications.mobileconfig", displayName: "Erosion Notification Settings", payloadType: "com.apple.notificationsettings", payload: ["NotificationSettings": settings])
                    SupervisionInstaller.install(profile)
                }
                .disabled(apps.isEmpty)
            }
        }
        .navigationTitle("Notification Settings")
    }
}

private struct SupervisionWebClipsView: View {
    @State private var label = ""
    @State private var url = ""
    @State private var removable = true
    @State private var fullScreen = false
    @State private var precomposed = false
    @State private var icon = Data()
    @State private var showPicker = false

    var body: some View {
        List {
            Section {
                TextField("Label", text: $label)
                TextField("URL", text: $url)
                    .textInputAutocapitalization(.never)
                    .autocorrectionDisabled()
                    .keyboardType(.URL)
                Toggle("Removable", isOn: $removable)
                Toggle("Full Screen", isOn: $fullScreen)
                Toggle("Precomposed Icon", isOn: $precomposed)
            } header: {
                HeaderLabel("Web Clip", symbol: "safari")
            }

            Section {
                Button {
                    showPicker = true
                } label: {
                    HStack {
                        Label("Choose Icon", systemImage: "photo")
                        Spacer()
                        if !icon.isEmpty { Image(systemName: "checkmark.circle.fill").foregroundStyle(.green) }
                    }
                }
                if !icon.isEmpty {
                    Button("Remove Icon", role: .destructive) { icon = Data() }
                }
            } header: {
                HeaderLabel("Icon", symbol: "app.gift")
            }

            Section {
                Button("Install Profile") {
                    let trimmed = url.trimmingCharacters(in: .whitespacesAndNewlines)
                    guard !label.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, !trimmed.isEmpty else {
                        Alertinator.shared.alert(title: "Missing Information", body: "Enter a label and URL first.")
                        return
                    }
                    guard let parsed = URL(string: trimmed), let scheme = parsed.scheme?.lowercased(), scheme == "http" || scheme == "https" else {
                        Alertinator.shared.alert(title: "Invalid URL", body: "The Web Clip URL must use http:// or https://.")
                        return
                    }
                    var payload: [String: Any] = [
                        "Label": label,
                        "URL": trimmed,
                        "IsRemovable": removable,
                        "FullScreen": fullScreen,
                        "Precomposed": precomposed
                    ]
                    if !icon.isEmpty { payload["Icon"] = icon }
                    let profile = SupervisionProfile(fileName: "Erosion-WebClip.mobileconfig", displayName: "Erosion Web Clip: \(label)", payloadType: "com.apple.webClip.managed", payload: payload)
                    SupervisionInstaller.install(profile)
                }
            }
        }
        .navigationTitle("Web Clips")
        .sheet(isPresented: $showPicker) {
            ImagePickerView { data in icon = data }
        }
    }
}
